title: Reese Ye # your name (or website title) here
logo: "/images/reesekevinye.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Professionally employed at the Australian Taxation Office for over 2 years. 
  <br><br>
  Currently a 3rd year student at the University of Technology Of Sydney (UTS), studying a degree in Computer science (Artifical Intellignece and Data Analytics) Honours. 
  <br><br>
  Expected to Complete my degree by 2023 with honours.
  <br><br>
  <a href="https://www.linkedin.com/in/reese-kevin-ye/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

<!-- HEADER -->
<div id="header_wrap" class="outer">
    <header class="inner">
      <a id="forkme_banner" href="{{ site.github.repository_url }}">View on GitHub</a>
      <h1 id="project_title">{{ site.title | default: site.github.repository_name }}</h1>
      <h2 id="project_tagline">{{ site.description | default: site.github.project_tagline }}</h2>
      {% if site.show_downloads %}
        <section id="downloads">
          <a class="zip_download_link" href="{{ site.github.zip_url }}">Download this project as a .zip file</a>
          <a class="tar_download_link" href="{{ site.github.tar_url }}">Download this project as a tar.gz file</a>
        </section>
      {% endif %}
      {% include nav.html %}
    </header>
</div>
